code-review-2
JohnPush/JS-Basic-hometasks pull request #2
Opened 2023-10-13 15:30 UTC by JohnPush

2023-10-13 21:03 UTC, Levitinn requested changes

2023-10-13 21:03 UTC, Levitinn commented on 7-converter/app.js
> +		case sum > 0 && currentCurrency === 'RUB' && targetCurrency === 'USD':
ты можешь написать вначале функции if(!sum) return ...... 
и не писать везде это условие в дальнейшем

2023-10-13 21:03 UTC, Levitinn commented on 8-crypto/app.js
> +    if (password === undefined || password === null ||password === '') {
тут лучше сделать if(!password) return вместо этого условия

2023-10-13 21:03 UTC, Levitinn commented on 8-crypto/app.js
> +            console.log(password);
слишком много операций с одинаковыми методами. попробуй как оптимизировать

2023-10-14 09:46 UTC, JohnPush commented on 7-converter/app.js
> +		case sum > 0 && currentCurrency === 'RUB' && targetCurrency === 'USD':
исправил на такой вариант if (!sum || sum < 0) return null;
чтобы не конвертировал отрицательные числа

2023-10-14 09:50 UTC, JohnPush commented on 8-crypto/app.js
> +    if (password === undefined || password === null ||password === '') {
исправил

2023-10-14 10:02 UTC, JohnPush commented on 8-crypto/app.js
> +            console.log(password);
попробовал. смотри.

2023-10-14 20:42 UTC, Levitinn approved these changes

2023-10-14 20:42 UTC, Levitinn commented on 8-crypto/app.js
> +        // } else {
лишние комменты удаляй перед мр

2023-10-14 20:46 UTC, merged