Feature/code review 3
JohnPush/JS-Basic-hometasks pull request #3
Opened 2023-10-14 20:57 UTC by JohnPush

2023-10-16 20:11 UTC, Levitinn requested changes

2023-10-16 20:11 UTC, Levitinn commented on 10-array-clean/app.js
> +function deleteOfElement (num) {
молодцом

2023-10-16 20:11 UTC, Levitinn commented on 11-date-array/app.js
> +console.log(newArr);
это не годится. очень длинная цепочка методов, еще и одинаковых. попробуй оптимизировать)

2023-10-16 20:11 UTC, Levitinn commented on 12-luna/app.js
> +    .replaceAll('-','')
а если сделать .split('-') станет короче цепочка методов. как думаешь?

2023-10-16 20:34 UTC, JohnPush commented on 12-luna/app.js
> +    .replaceAll('-','')
я думаю если вместо 
.replaceAll('-','')
.split('')

сделаю
.split('-')

будет хуже, в первом случае я получаю результат
['4', '5', '6', '1', '2', '6', '1', '2', '1', '2', '3', '4', '5', '4', '6', '4']
а втором случае получу
['4561', '2612', '1234', '5464']

2023-10-18 14:35 UTC, JohnPush commented on 11-date-array/app.js
> +console.log(newArr);
посмотри. Сделать еще короче не получается. И плюс проблема в том как добавить 0 перед днем или месяцем если их значение от 1 до 9

2023-10-18 21:38 UTC, Levitinn requested changes

2023-10-18 21:38 UTC, Levitinn commented on 11-date-array/app.js
> +console.log(date(arr));
это слишком тяжело воспринимать. если в твоем решении, ты видишь многократное использование методов filter, map или др. , то это явный звоночек о том, что ты идешь по сложному пути. попробуй привести каждую строку к одному виду и проверять дату, внутри строки, на валидность, используя new Date (или другие методы работы с датой)

2023-10-23 14:51 UTC, Levitinn approved these changes
ура) не очень люблю использовать switch, но теперь для восприятия все легко. принимаю

2023-10-23 14:58 UTC, merged